### ISSUE TITLE
Active Directory based account can still login after AD Account has been disabled

### ISSUE THREAD

**Issue by m1ndgames** [matrix-org/matrix-synapse-ldap3#113]
**Describe the bug**
We run a matrix server which is connected to the companies AD server. An employee has left the company so we disabled his AD
Account. We would expect that he would now be unable to access the companies matrix server, but that's not the case. He is still online and we don't see a way to make sure people don't have access anymore after leaving the company.

**To Reproduce**

- Configure synapse to allow AD access
- Create AD user
- Login with AD user Account
- Disable AD User on AD Server
- Login with AD user Account

**Expected behavior**
User can't login anymore.

**Desktop (please complete the following information):**
 - All clients are affected.

**Smartphone (please complete the following information):**
 - All clients are affected.

**Comment by clokep** [comment]
There's a couple of pieces to this:

* When an account is disabled in LDAP there's no way for Synapse to know that this has occurred. In order to log out current sessions you would need to disable their account in LDAP. (There's an [admin API](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#id4) to do this.)
* I'm surprised that a user is still able to login when disabled in AD -- is it return an error when the user attempts to login?

Something to look into -- is `password_config.localdb_enabled` configured to `false` in your Synapse config?

**Comment by richvdh** [comment]
It looks like we don't have the answers we need to investigate this, so I'm going to go ahead and close it.

**Comment by banym** [comment]
I can second this problem. I have the same problem and it still exists. 

What I understand is that it should be possible to filter if the account is enables or not. For example: 
(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))

But in my understanding a disabled LDAP/AD account should never be able to login as long as the account is disabled.
