### ISSUE TITLE
Can login only with lowercase username

### ISSUE THREAD

**Issue by enannos** [matrix-org/matrix-synapse-ldap3#72]
Hello,

it looks like that, when the user tries to login with uppercase or a combination of uppercase and lowercase, the login fails. 
The only way to login using the Active Directory credentials is to use only lowercase. 

In the configuration we have:
     attributes:
        uid: "sAMAccountName"
        mail: "mail"
        name: "displayName"

Is there a way to allow the users to login without caring about the case sensitivity? 

Thank you in advance

**Comment by Stapper** [comment]
Any idea where this issue is coming from? if someone can point me in the right direction, I can maybe try to fix this, as it has been irritating me as well.

**Comment by ocemo** [comment]
I don't think Synapse is able to handle uppercase names at all. The best way to fix it would be to have the matrix-synapse-ldap3 plugin translate things into lowercase for everything.

**Comment by horstepipe** [comment]
> 
> 
> I don't think Synapse is able to handle uppercase names at all. The best way to fix it would be to have the matrix-synapse-ldap3 plugin translate things into lowercase for everything.

I'm just running into the same problem. 
I want to use ldap. my usernames are already tied because of another service we're using. Sure, I can tell them not tu use uppercase for usernames at Synapse, but for sure this will confuse some of them to use their user name without uppercase here, but with uppercase there.
